sudo: required
dist: trusty

before_install:
- sudo apt-get -qq update && sudo apt-get install texlive
script:
- xelatex -interaction=nonstopmode -halt-on-error -job-name=Sezer_Tanriverdioglu_CV main.tex

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "*.pdf"
  skip_cleanup: true
  on:
    repo: microgenius/Curriculum-Vitae
    branch: master
    tags: true